import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans, Geist_Mono } from "next/font/google";
import ToastProvider from "../components/ui/toast-provider";
import AosProvider from "../components/ui/aos-provider";
import { getCurrentUser } from "../lib/action/auth.action";
import "./globals.css";


const dmSans = DM_Sans({
 variable: "--font-dm-sans",
 subsets: ["latin", "latin-ext"],
 weight: ["300", "400", "500", "600", "700"],
});


const cormorantGaramond = Cormorant_Garamond({
 variable: "--font-cormorant-garamond",
 subsets: ["latin", "latin-ext"],
 weight: ["300", "400", "500", "600", "700"],
});


const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});


export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};


export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 // action-(check role layout tổng)
 const currentUser = await getCurrentUser();


 return (
   <html
     lang="en"
     className={`${dmSans.variable} ${cormorantGaramond.variable} ${geistMono.variable} h-full antialiased`}
   >
     <body
       className="min-h-full flex flex-col"
       data-role={currentUser?.role ?? "GUEST"}
     >
       <ToastProvider>
         {children}
         <AosProvider />
       </ToastProvider>
     </body>
   </html>
 );
}



